# -*- coding: utf-8 -*-
"""Utilization_Report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WkrkQ00wv22wzBHO0AizNExyQwX_XlgL
"""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

def send_email():
    # Email content
    from_address = "kartik@project-lithium.com"
    to_address = "kartikpande12@gmail.com"
    subject = "Daily Report"
    report_link = "https://prod-apnortheast-a.online.tableau.com/#/site/lithiumurbantech/workbooks/2223869/views"

    # Create the HTML body with a clickable link
    body = f"""
    <html>
    <body>
        <p>Hello,</p>
        <p>This is your daily report for {datetime.now().strftime('%Y-%m-%d')}.</p>
        <p>Please view the report <a href="{report_link}">here</a>.</p>
    </body>
    </html>
    """

    # Set up the MIME
    msg = MIMEMultipart()
    msg['From'] = from_address
    msg['To'] = to_address
    msg['Subject'] = subject

    # Attach the HTML body
    msg.attach(MIMEText(body, 'html'))

    # Set up the SMTP server
    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.starttls()
    server.login(from_address, 'lpolrrwyvnffyynv')  # Use app password if needed for Gmail

    # Send the email
    server.sendmail(from_address, to_address, msg.as_string())
    server.quit()

if __name__ == "__main__":
    send_email()

