name: Send Daily Email

on:
  schedule:
    - cron: "30 2 * * *"  # This will trigger the workflow at 08:00 AM IST
  workflow_dispatch:  # Allows you to run the workflow manually if needed

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install smtplib email datetime

    - name: Run email script
      run: |
        python utilization_report.py  # Make sure this matches your script name
